version: '2.1'

services:
  eureka:
    build: eurekaserver
    mem_limit: 350m
    environment:
      - JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2
    ports:
      - "8761:8761"

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2
    build: gateway
    mem_limit: 350m
    ports:
      - "8080:8080"

  athlete-service:
    build: athlete-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8005:8080"
#    depends_on:
#      - mongos

  user-service:
    build: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8006:8080"
#    depends_on:
#      - mongos

  ado-service:
    build: ado-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8007:8080"
#    depends_on:
#      - mongos

#  mongos:
#    image: 'bitnami/mongodb-sharded:latest'
#    environment:
#      - MONGODB_SHARDING_MODE=mongos
#      - MONGODB_CFG_PRIMARY_HOST=mongodb-configsvr-primary
#      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_ROOT_PASSWORD=123456
#      - MONGODB_ADVERTISED_HOSTNAME=mongos
#    ports:
#      - "27017:27017"
#
#  mongodb-shard0-primary:
#    image: 'bitnami/mongodb-sharded:latest'
#    environment:
#      - MONGODB_SHARDING_MODE=shardsvr
#      - MONGODB_MONGOS_HOST=mongos
#      - MONGODB_ROOT_PASSWORD=123456
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=shard0
#      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0-primary
#    ports:
#      - "27018:27017"
#
#  mongodb-shard1-primary:
#    image: 'bitnami/mongodb-sharded:latest'
#    environment:
#      - MONGODB_SHARDING_MODE=shardsvr
#      - MONGODB_MONGOS_HOST=mongos
#      - MONGODB_ROOT_PASSWORD=123456
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=shard1
#      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard1-primary
#    ports:
#      - "27019:27017"
#
#  mongodb-shard2-primary:
#    image: 'bitnami/mongodb-sharded:latest'
#    environment:
#      - MONGODB_SHARDING_MODE=shardsvr
#      - MONGODB_MONGOS_HOST=mongos
#      - MONGODB_ROOT_PASSWORD=123456
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=shard2
#      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard2-primary
#    ports:
#      - "27020:27017"
#
#  mongodb-configsvr-primary:
#    image: 'bitnami/mongodb-sharded:latest'
#    environment:
#      - MONGODB_SHARDING_MODE=configsvr
#      - MONGODB_ROOT_PASSWORD=123456
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=config-replicaset
#      - MONGODB_ADVERTISED_HOSTNAME=mongodb-configsvr-primary