global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service1'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8006']
        labels:
          application: 'user-service'
          
  - job_name: 'user-service2'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8004']
        labels:
          application: 'user-service'
          
  - job_name: 'gateway'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'gateway'