server.port: 7003
spring.application.name: athlete-service
spring.redis.host: ${app.redis-server}
spring.redis.port: 6379
app.eureka-server: localhost
logging:
    file: ./logs/athlete-serice.log
    level:
     root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
spring.data.mongodb.uri: mongodb://root:123456@52.190.2.8:27017/wada?authSource=admin&readPreference=primaryPreferred&appname=MongoDB%20Compass&retryWrites=true&ssl=false
spring.data.mongodb.authentication-database: admin
spring.data.mongodb.auto-index-creation: false
management.endpoints.web.exposure.include: health,info,prometheus
---
spring.profiles: docker
server.port: 8080
app.eureka-server: eureka
app.redis-server: redis-server